INSERT INTO Article(ID, TITLE, CONTENT) VALUES (1, '가가가가', '1111');
INSERT INTO Article(ID, TITLE, CONTENT) VALUES (2, '나나나나', '2222');
INSERT INTO Article(ID, TITLE, CONTENT) VALUES (3, '다다다다', '3333');
INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES (1, 'aaa@aaa.com', '1111');
INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES (2, 'bbb@bbb.com', '2222');
INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES (3, 'ccc@ccc.com', '3333');
