INSERT INTO Article(TITLE, CONTENT) VALUES ('가가가가', '1111');
INSERT INTO Article(TITLE, CONTENT) VALUES ('나나나나', '2222');
INSERT INTO Article(TITLE, CONTENT) VALUES ('다다다다', '3333');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES ('aaa@aaa.com', '1111');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES ('bbb@bbb.com', '2222');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES ('ccc@ccc.com', '3333');
